version: '2'
services:
    testfood-app:
        image: testfood
        external_links:
            - testfood-mssql:mssql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testfood-mssql:
        extends:
            file: mssql.yml
            service: testfood-mssql
